{
    "name": "Registro Fincas",
    "version": "18.0.0.0.0",
    "category": "Code",
    "sequence": 14,
    "author": "AlparData SAS",
    "website": "www.alpardata.com.ar",
    "license": "AGPL-3",
    "summary": "",
    "depends": [],
    "data": [],
    "demo": [],
    "installable": False,
    "auto_install": False,
    "application": False,
}